/**
 * Plain-language gloss for every technical term that surfaces in the UI.
 *
 * Used by <HelpDot term="…" /> and <TermHelp term="…">…</TermHelp> from
 * components/help-dot.tsx. Keep `short` to one or two sentences — the
 * popover body is intentionally tight; deeper detail lives at /about.
 */

export type GlossaryKey =
  | "xG"
  | "Elo"
  | "SHAP"
  | "log-loss"
  | "Brier"
  | "RPS"
  | "calibration"
  | "reliability"
  | "Monte Carlo"
  | "Dixon-Coles"
  | "R32"
  | "R16"
  | "QF"
  | "SF"
  | "best-3rd"
  | "model version"
  | "FT_WHISTLE"
  | "AET"
  | "joint score probability"
  | "realisation"
  | "conditional locks"
  | "delta"
  | "host venue";

export type GlossaryEntry = {
  /** Full, screen-reader-friendly name. */
  name: string;
  /** One to two plain-language sentences. */
  short: string;
  /** Optional deep link into the methodology page. */
  link?: `/about#${string}`;
};

export const GLOSSARY: Record<GlossaryKey, GlossaryEntry> = {
  xG: {
    name: "Expected goals (xG)",
    short:
      "Average number of goals a team would score given the quality of shots they took. Lets us judge underlying performance independently of finishing luck.",
    link: "/about#match-model",
  },
  Elo: {
    name: "Elo rating",
    short:
      "A team-strength number that grows on wins and shrinks on losses. A 100-point gap on neutral ground is roughly +5–7 percentage points of win probability.",
    link: "/about#lineage",
  },
  SHAP: {
    name: "SHAP feature attribution",
    short:
      "A breakdown of which inputs pushed the model's prediction up or down — Elo gap, recent form, home advantage, etc. Positive bars favour the outcome; negative bars work against it.",
    link: "/about#stage-1-enhancements-this-pr",
  },
  "log-loss": {
    name: "Log-loss",
    short:
      "Penalises confident wrong predictions more than cautious ones. Lower is better. A coin-flip baseline scores 1.099; perfect prediction scores 0.",
    link: "/about#backtest-gates",
  },
  Brier: {
    name: "Brier score",
    short:
      "Squared error between predicted and observed probabilities for each outcome. Lower is better. The climatological baseline for 1X2 is around 0.22.",
    link: "/about#backtest-gates",
  },
  RPS: {
    name: "Ranked Probability Score",
    short:
      "Penalises predictions that miss the order of outcomes — predicting a draw when home wins hurts less than predicting an away win. Lower is better.",
    link: "/about#backtest-gates",
  },
  calibration: {
    name: "Calibration",
    short:
      "When the model says 30%, things should happen about 30% of the time. The reliability diagram is the visual check.",
    link: "/about#backtest-gates",
  },
  reliability: {
    name: "Reliability diagram",
    short:
      "A scatter plot of predicted vs. observed frequencies. Points on the diagonal mean the model is well calibrated.",
    link: "/about#backtest-gates",
  },
  "Monte Carlo": {
    name: "Monte Carlo simulation",
    short:
      "We play the rest of the tournament thousands of times (5,000 by default) and count how often each team advances or wins.",
    link: "/about#tournament-simulator-tiebreakers",
  },
  "Dixon-Coles": {
    name: "Dixon-Coles correction",
    short:
      "A tweak to the standard Poisson model that gives 0-0, 1-0, 0-1, and 1-1 their (slightly higher) real-world frequencies.",
    link: "/about#match-model",
  },
  R32: {
    name: "Round of 32",
    short:
      "The opening knockout round — the top two from each of the 12 groups, plus the 8 best third-placed teams, into a 32-team bracket.",
  },
  R16: { name: "Round of 16", short: "Knockout round of 16 teams (8 matches)." },
  QF: { name: "Quarterfinals", short: "Knockout round of 8 teams (4 matches)." },
  SF: { name: "Semifinals", short: "Knockout round of 4 teams (2 matches)." },
  "best-3rd": {
    name: "Best-third advancement",
    short:
      "8 of the 12 third-placed teams qualify for the Round of 32, ranked across groups by points → goal difference → goals scored. The other 4 are eliminated.",
  },
  "model version": {
    name: "Model version",
    short:
      "A label refreshed every time we retrain or change a coefficient. Lets you tell when a forecast was generated by a different model.",
  },
  FT_WHISTLE: {
    name: "Full-time whistle",
    short: "The end of regulation play — 90 minutes plus any added time.",
  },
  AET: {
    name: "After extra time",
    short:
      "Decided in the 30 minutes of extra time, before any penalty shootout.",
  },
  "joint score probability": {
    name: "Joint score probability",
    short:
      "The chance of a specific final score (e.g. 2-1). Each heatmap cell is one possible scoreline.",
  },
  realisation: {
    name: "One realisation",
    short:
      "A single playthrough of the knockout bracket using one random seed. Run multiple seeds to compare possible futures.",
  },
  "conditional locks": {
    name: "Conditional locks",
    short:
      "Pin a known knockout result (e.g. “Brazil beat Mexico in the R16”). The model then plays out everything else around that fixed outcome.",
  },
  delta: {
    name: "Delta (Δ)",
    short:
      "Change since the previous snapshot. For FIFA rank, lower numbers are better (rank 1 is best), so a negative Δ means climbing the table.",
  },
  "host venue": {
    name: "Host venue",
    short:
      "One of the 16 stadiums hosting matches in 2026 — 11 in the USA, 3 in Mexico, 2 in Canada.",
  },
};
