/**
 * Hand-rolled core types until `pnpm gen:types` runs against a live FastAPI.
 *
 * The full type set lives in `src/lib/api-types.ts` (generated by
 * openapi-typescript). The types in this file are a tight subset used by
 * shared components so the app type-checks before the backend is reachable.
 */

export interface HealthResponse {
  status: string;
  model_fitted: boolean;
  model_teams_n: number;
  model_fit_at: string | null;
  model_version: string | null;
  elo_snapshot_date: string | null;
  elo_snapshot_age_days: number | null;
  shootout_model_loaded: boolean;
  group_assignment_source: string;
}

export interface FixtureSummary {
  match_id: number;
  date: string;
  utc_kickoff: string | null;
  home_team: string;
  away_team: string;
  group: string;
  city: string;
  country: string;
  neutral: boolean;
}

export interface OutcomeProbabilities {
  home_win: number;
  draw: number;
  away_win: number;
}

export interface Scoreline {
  home_goals: number;
  away_goals: number;
  probability: number;
}

export interface BlendedOutcome {
  poisson: OutcomeProbabilities;
  xgb: OutcomeProbabilities;
  blended: OutcomeProbabilities;
  weight: number;
}

export interface PredictionResponse {
  home_team: string;
  away_team: string;
  neutral: boolean;
  expected_home_goals: number;
  expected_away_goals: number;
  outcome: OutcomeProbabilities;
  top_scorelines: Scoreline[];
  score_matrix: number[][] | null;
  blend: BlendedOutcome | null;
}

export interface FixtureWithPrediction {
  fixture: FixtureSummary;
  prediction: PredictionResponse;
}

export interface TeamAssetsResponse {
  team: string;
  crest_url: string | null;
  kit_home_color: string | null;
  kit_away_color: string | null;
  stadium_name: string | null;
  stadium_capacity: number | null;
  stadium_city: string | null;
  stadium_country: string | null;
}

export interface PerMatchCalibrationRow {
  match_date: string;
  home_team: string;
  away_team: string;
  home_score: number;
  away_score: number;
  p_home: number;
  p_draw: number;
  p_away: number;
  observed: string;
  log_loss: number;
  brier: number;
  rps: number;
  model_version: string;
}

export interface WC2026TrackRecord {
  n_completed: number;
  log_loss: number | null;
  brier: number | null;
  rps: number | null;
  per_match: PerMatchCalibrationRow[];
}
